apiVersion: v1
kind: Secret
metadata:
    name: payments-api
type: Opaque
stringData:
    PAYMENTS_API_KEY: ENC[AES256_GCM,data:eFRCVCR2LghYDUcEapvN4Ncgc7WH/TZmdR2pfKRI,iv:2nsVxT5PKsMxOBPT5Upq4Rh8/uiXzabdg3JVyWK57KY=,tag:6NytlGiSIl+VQ0/hdKo3GQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3SFJsbElIcklyeXQzbzJs
            ZzRXSVRDZ1lMSzU1NTR2UnVKTzkxUDR4V0Y4CnVqRkNFRCsvRkxHaDg4N1NLR2pl
            Y3JJNWhuZTF5TjAwUDhrVUc5c21tTXMKLS0tIGs1S1dSY0I2a0dxMW1QUEZDVldY
            YUtBK3ZuTkJ2L1A5QXU4OUV0YjM1aVkKRJVwjzuLvV4oq+urKkkrz9w7OtvbSzPf
            RJlJCCieBYLh+2iXYAoL92Eh/FY1KR76BdBC4CB5oen1h+uWP9vnAA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dyktvjsa8zkfqs6vzxcggyfysakep7x6lvrzntlh532qwy9xcdpsxlvz2p
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T04:41:42Z"
    mac: ENC[AES256_GCM,data:acgQi7Cr01pECvGhSN2xuZcqLTFmS1GDIiROiHKTWq8KCaD0vQDOOKm0G0zGUwTST53TOmY12QfVhOKEQvXdJG8xFf9zrIXRhsuy1YBf7MsSh4KVMJYagU+34+jbO+WUtOj9ovbmBcDHLZrBNeoAsLwgwGy9RO6XYdZx5wP4ObA=,iv:ejzx3g/BLXhVrkJUYDHjVCAJaVaxOvNiaEICrIjBuA0=,tag:6H2l3OLLvh6TLX/KSRZY/g==,type:str]
    version: 3.13.3
